# Generated by Django 4.0.1 on 2022-04-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=60)),
                ('dis', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('Is_admin', models.IntegerField()),
                ('membership_date', models.DateField(null=True)),
                ('membership_ex_date', models.DateField(null=True)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Membership_package',
            fields=[
                ('Member_id', models.AutoField(primary_key=True, serialize=False)),
                ('Package_name', models.CharField(max_length=50)),
                ('m_description', models.CharField(max_length=500)),
                ('Ammount', models.IntegerField()),
                ('validity', models.IntegerField()),
                ('pack_img', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Membership_package',
            },
        ),
        migrations.CreateModel(
            name='resort',
            fields=[
                ('Resort_id', models.AutoField(primary_key=True, serialize=False)),
                ('Resort_address', models.CharField(max_length=200)),
                ('r_description', models.CharField(max_length=1000)),
                ('cover_image', models.CharField(max_length=150)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.city')),
            ],
            options={
                'db_table': 'resort',
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_des', models.CharField(max_length=500)),
                ('room_name', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('room_img', models.CharField(max_length=150)),
                ('Resort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.resort')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_d', models.CharField(max_length=100)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.room')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=100)),
                ('review_date', models.DateField()),
                ('Resort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.resort')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.customer')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='resort_owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_email', models.EmailField(max_length=50)),
                ('owner_pass', models.CharField(max_length=30)),
                ('owner_contactno', models.CharField(max_length=15)),
                ('owner_address', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True)),
                ('Resort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.resort')),
            ],
            options={
                'db_table': 'resort_owner',
            },
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=50)),
                ('ammount', models.IntegerField()),
                ('p_Description', models.CharField(max_length=1000)),
                ('image_path', models.CharField(max_length=100)),
                ('package_date', models.DateField()),
                ('Resort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.resort')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.room')),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('Gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_image', models.CharField(max_length=150)),
                ('Resort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.resort')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('feedback_date', models.DateField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.customer')),
                ('package_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resort_admin.package')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resort_admin.room')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_description', models.CharField(max_length=100)),
                ('f_img', models.CharField(max_length=150, null=True)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.package')),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='Member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resort_admin.membership_package'),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('checkIn_date', models.DateField()),
                ('checkOut_date', models.DateField()),
                ('payment_status', models.CharField(max_length=20)),
                ('booking_status', models.IntegerField()),
                ('total', models.IntegerField()),
                ('Resort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.resort')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.customer')),
                ('package_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resort_admin.package')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resort_admin.room')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=50)),
                ('area_pincode', models.IntegerField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort_admin.city')),
            ],
            options={
                'db_table': 'area',
            },
        ),
    ]
