# Generated by Django 4.0.1 on 2022-04-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='area',
        ),
    ]
