# Generated by Django 4.0.1 on 2022-04-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort_admin', '0002_delete_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_date',
        ),
    ]
