# Generated by Django 4.0.1 on 2022-04-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort_admin', '0003_remove_package_package_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='f_img',
        ),
    ]
